In [1]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [3]:
pip install xgboost

  Obtaining dependency information for xgboost from https://files.pythonhosted.org/packages/24/ec/ad387100fa3cc2b9b81af0829b5ecfe75ec5bb19dd7c19d4fea06fb81802/xgboost-2.0.3-py3-none-win_amd64.whl.metadata
   ---------------------------------------- 0.0/99.8 MB ? eta -:--:--
   ---------------------------------------- 0.2/99.8 MB 4.7 MB/s eta 0:00:22
   ---------------------------------------- 0.3/99.8 MB 3.2 MB/s eta 0:00:32
   ---------------------------------------- 0.3/99.8 MB 3.2 MB/s eta 0:00:32
   ---------------------------------------- 0.4/99.8 MB 2.1 MB/s eta 0:00:47
   ---------------------------------------- 0.6/99.8 MB 2.3 MB/s eta 0:00:43
   ---------------------------------------- 0.7/99.8 MB 2.6 MB/s eta 0:00:38
   ---------------------------------------- 1.0/99.8 MB 2.9 MB/s eta 0:00:34
   ---------------------------------------- 1.1/99.8 MB 2.9 MB/s eta 0:00:34
   ---------------------------------------- 1.2/99.8 MB 2.9 MB/s eta 0:00:35
    ----------------------------

In [4]:
import pandas as pd
import numpy as np 

In [19]:
data =pd.read_csv('Fraud.csv')

In [6]:
data.head()

step      type    amount     nameOrig  oldbalanceOrg  newbalanceOrig  \
0     1   PAYMENT   9839.64  C1231006815       170136.0       160296.36   
1     1   PAYMENT   1864.28  C1666544295        21249.0        19384.72   
2     1  TRANSFER    181.00  C1305486145          181.0            0.00   
3     1  CASH_OUT    181.00   C840083671          181.0            0.00   
4     1   PAYMENT  11668.14  C2048537720        41554.0        29885.86   

      nameDest  oldbalanceDest  newbalanceDest  isFraud  isFlaggedFraud  
0  M1979787155             0.0             0.0        0               0  
1  M2044282225             0.0             0.0        0               0  
2   C553264065             0.0             0.0        1               0  
3    C38997010         21182.0             0.0        1               0  
4  M1230701703             0.0             0.0        0               0

In [7]:
data.tail()


step      type      amount     nameOrig  oldbalanceOrg  \
6362615   743  CASH_OUT   339682.13   C786484425      339682.13   
6362616   743  TRANSFER  6311409.28  C1529008245     6311409.28   
6362617   743  CASH_OUT  6311409.28  C1162922333     6311409.28   
6362618   743  TRANSFER   850002.52  C1685995037      850002.52   
6362619   743  CASH_OUT   850002.52  C1280323807      850002.52   

         newbalanceOrig     nameDest  oldbalanceDest  newbalanceDest  isFraud  \
6362615             0.0   C776919290            0.00       339682.13        1   
6362616             0.0  C1881841831            0.00            0.00        1   
6362617             0.0  C1365125890        68488.84      6379898.11        1   
6362618             0.0  C2080388513            0.00            0.00        1   
6362619             0.0   C873221189      6510099.11      7360101.63        1   

         isFlaggedFraud  
6362615               0  
6362616               0  
6362617               0  
6362618               0  
6362619               0

In [7]:
data.shape


(6362620, 11)

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6362620 entries, 0 to 6362619
Data columns (total 11 columns):
 #   Column          Dtype  
---  ------          -----  
 0   step            int64  
 1   type            object 
 2   amount          float64
 3   nameOrig        object 
 4   oldbalanceOrg   float64
 5   newbalanceOrig  float64
 6   nameDest        object 
 7   oldbalanceDest  float64
 8   newbalanceDest  float64
 9   isFraud         int64  
 10  isFlaggedFraud  int64  
dtypes: float64(5), int64(3), object(3)
memory usage: 534.0+ MB


In [15]:
data['step']

AttributeError: 'Series' object has no attribute 'range'

In [20]:
data.isna().sum()

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    0
isFraud           0
isFlaggedFraud    0
dtype: int64

### No Missing values


In [21]:
data.isFraud.value_counts()

0    6354407
1       8213
Name: isFraud, dtype: int64

In [22]:
data.isFlaggedFraud.value_counts()

0    6362604
1         16
Name: isFlaggedFraud, dtype: int64

In [23]:
# cols = {'Category': ['CASH-IN', 'CASH-OUT', 'DEBIT', 'PAYMENT', 'TRANSFER']}

In [25]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()


In [26]:
data['type']=label_encoder.fit_transform(data['type'])

In [28]:
data['type'].value_counts()

1    2237500
3    2151495
0    1399284
4     532909
2      41432
Name: type, dtype: int64

In [31]:
data.drop(['nameOrig','nameDest'],axis=1,inplace=True)

In [37]:
fraud=data[data['isFraud']==1]

In [38]:
nonFraud=data[data['isFraud']==0]

In [42]:
fraud.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8213 entries, 2 to 6362619
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   step            8213 non-null   int64  
 1   type            8213 non-null   int32  
 2   amount          8213 non-null   float64
 3   oldbalanceOrg   8213 non-null   float64
 4   newbalanceOrig  8213 non-null   float64
 5   oldbalanceDest  8213 non-null   float64
 6   newbalanceDest  8213 non-null   float64
 7   isFraud         8213 non-null   int64  
 8   isFlaggedFraud  8213 non-null   int64  
dtypes: float64(5), int32(1), int64(3)
memory usage: 609.6 KB


In [43]:
nonFraud=nonFraud.sample(8213)

In [44]:
nonFraud.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8213 entries, 848074 to 5266856
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   step            8213 non-null   int64  
 1   type            8213 non-null   int32  
 2   amount          8213 non-null   float64
 3   oldbalanceOrg   8213 non-null   float64
 4   newbalanceOrig  8213 non-null   float64
 5   oldbalanceDest  8213 non-null   float64
 6   newbalanceDest  8213 non-null   float64
 7   isFraud         8213 non-null   int64  
 8   isFlaggedFraud  8213 non-null   int64  
dtypes: float64(5), int32(1), int64(3)
memory usage: 609.6 KB


In [32]:
X=

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6362620 entries, 0 to 6362619
Data columns (total 9 columns):
 #   Column          Dtype  
---  ------          -----  
 0   step            int64  
 1   type            int32  
 2   amount          float64
 3   oldbalanceOrg   float64
 4   newbalanceOrig  float64
 5   oldbalanceDest  float64
 6   newbalanceDest  float64
 7   isFraud         int64  
 8   isFlaggedFraud  int64  
dtypes: float64(5), int32(1), int64(3)
memory usage: 412.6 MB


In [46]:
newData=pd.concat([fraud,nonFraud])

In [47]:
X=newData.drop('isFraud',axis=1)
y=newData['isFraud']

In [49]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16426 entries, 2 to 5266856
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   step            16426 non-null  int64  
 1   type            16426 non-null  int32  
 2   amount          16426 non-null  float64
 3   oldbalanceOrg   16426 non-null  float64
 4   newbalanceOrig  16426 non-null  float64
 5   oldbalanceDest  16426 non-null  float64
 6   newbalanceDest  16426 non-null  float64
 7   isFlaggedFraud  16426 non-null  int64  
dtypes: float64(5), int32(1), int64(2)
memory usage: 1.1 MB


In [50]:
y.info()

<class 'pandas.core.series.Series'>
Int64Index: 16426 entries, 2 to 5266856
Series name: isFraud
Non-Null Count  Dtype
--------------  -----
16426 non-null  int64
dtypes: int64(1)
memory usage: 256.7 KB


In [51]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

### Model evaluator

In [76]:
from sklearn.metrics import f1_score, recall_score, confusion_matrix

def evaluate_classification(y_true, y_pred):
    """
    Function to evaluate a classification model.

    Args:
    - y_true (array-like): True labels.
    - y_pred (array-like): Predicted labels.

    Returns:
    - f1 (float): F1 score.
    - recall (float): Recall score.
    - cm (array): Confusion matrix.
    """
    # Calculate F1 score
    f1 = f1_score(y_true, y_pred)
    
    # Calculate recall
    recall = recall_score(y_true, y_pred)
    
    # Calculate confusion matrix
    cm = confusion_matrix(y_true, y_pred)
    
    return f1, recall, cm

# Example usage:
# Assuming y_test and y_pred are available from a classification model
# Evaluate the model
# f1_score, recall_score, confusion_matrix = evaluate_classification(y_test, y_pred)

# # Output the evaluation metrics
# print("F1 Score:", f1_score)
# print("Recall Score:", recall_score)
# print("Confusion Matrix:\n", confusion_matrix)


## Logistic Regression

In [72]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

model_log = LogisticRegression()

# Train the model on the training data
model_log.fit(X_train, y_train)

# Predict on the testing data
y_pred_log = model_log.predict(X_test)

# Calculate accuracy
accuracy_log = accuracy_score(y_test, y_pred_log)
print("Accuracy:", accuracy_log)

Accuracy: 0.9001825928180158


In [77]:
f1,recall,conf=evaluate_classification(y_test,y_pred_log)

In [78]:
f1

0.9003039513677812

In [79]:
recall

0.8981200727713766

In [80]:
conf

array([[1477,  160],
       [ 168, 1481]], dtype=int64)

## Decision Tree

In [59]:
from sklearn.tree import DecisionTreeClassifier

model_dtree = DecisionTreeClassifier()

# Train the model on the training data
model_dtree.fit(X_train, y_train)

# Predict on the testing data
y_pred_dtree = model_dtree.predict(X_test)

# Calculate accuracy
accuracy_dtree = accuracy_score(y_test, y_pred_dtree)
print("Accuracy:", accuracy_dtree)


Accuracy: 0.9826536822884967


In [82]:
f1,recall,conf=evaluate_classification(y_test,y_pred_dtree)

In [83]:
f1

0.9827742520398912

In [84]:
recall

0.9860521528198909

In [85]:
conf

array([[1603,   34],
       [  23, 1626]], dtype=int64)

In [86]:
from sklearn.ensemble import RandomForestClassifier
model_rf = RandomForestClassifier()

# Train the model on the training data
model_rf.fit(X_train, y_train)

# Predict on the testing data
y_pred_rf = model_rf.predict(X_test)

# Calculate accuracy
accuracy_rf = accuracy_score(y_test, y_pred_rf)
print("Accuracy:", accuracy_rf)


Accuracy: 0.9872185027388922


In [87]:
f1,recall,conf=evaluate_classification(y_test,y_pred_dtree)

In [88]:
f1

0.9827742520398912

In [89]:
recall

0.9860521528198909

In [90]:
conf

array([[1603,   34],
       [  23, 1626]], dtype=int64)

In [64]:
import xgboost as xgb
model_xgb = xgb.XGBClassifier()

# Train the model on the training data
model_xgb.fit(X_train, y_train)

# Predict on the testing data
y_pred_xgb = model_xgb.predict(X_test)

# Calculate accuracy
accuracy_xgb = accuracy_score(y_test, y_pred_xgb)
print("Accuracy:", accuracy_xgb)


Accuracy: 0.9923919659160073


In [91]:
f1,recall,conf=evaluate_classification(y_test,y_pred_dtree)

In [92]:
f1

0.9827742520398912

In [94]:
recall

0.9860521528198909

In [95]:
conf

array([[1603,   34],
       [  23, 1626]], dtype=int64)